### ISSUE TITLE
Advanced search view with field controls for search

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-search-react#3]
- [x] **Advanced Search** - wrapper component that can be customized with custom field filters
    - Props
        - **schema: Schema\<T>**
        - **fields: (options: AdvancedSearchOptions\<T>) => React.ReactElement\<any>** - A callback method to create the field components for the query. The components can trigger a query update, get field settings and schema from the derived **options** object
        - **onQueryChanged (q: Query\<T>) => void** - Triggered when the query changes
        - **style?: React.CSSProperties**  - Optional style definitions for the container object
 - [x] Aggregate the subqueries from the field controls with an *and operator*
wrapper component

**Comment by gallayl** [comment]
This can be tested on https://sn-search-react-dev.netlify.com/

**Comment by kultsar** [comment]
- [ ] "Triggered when the query changes" - I changed the query, but the search is not triggered, I need to click the Send button or press Enter. Is this a requirement or I misunderstood this? Otherwise seems ok for me, could go to Done.

**Comment by gallayl** [comment]
That doesn't mean that will trigger sending the query itself, it depends on the component usage (and now it's implemented in the example app, not in the component). The *onQueryChanged* callback only refreshes the "Full query" window, you may have take care of setting up a site, cors, etc..., but you can try the component without even sending a simple request and checking the query.
The example app is a lightweight and minimistic "showcase" at the moment and it's purpose is just to check and validate the search query (the styling /layout is also out of scope for now), I think if we need advanced features or have concrete expectations we should add it as a task for https://github.com/sensenet/sn-search-react/issues/8
