### ISSUE TITLE
Custom control for reference (e.g. user) fields

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-search-react#6]
- [x] Create a custom control for filtering references

**Comment by gallayl** [comment]
Questions:
 - If I have multiple [AllowedTypes](http://wiki.sensenet.com/Reference_Field) defined on the Schema, should I search for a reference with a **Type** or a **TypeIs** filter? (let's say if I search for a user and I have inherited user types)
 - *(can be postponed, I think picking a single value can be enough for the first version)* Can I pick multiple references? (e.g. I'm searching for a *group* with multiple users)
    - In case of multiple references, what query operator should I use? (and / or / from settings)

**Comment by kultsar** [comment]
I think both answers depend on the specific business requirements, and they can be various. Since this is a sample/demo app, I could imagine solutions that are interesting but maybe not require too much effort. I would vote for *TypeIs* and single value now, and multiple references made possible later with "or" setting.
